Repository WildCodeSchool/2023-03-js-TLSE-P2-cookbuddy, pull requests merged in 2023-05, with the labels that each got.

#36 S4_F02_US3_iphone-fixes: Fixing the inputs and filters issues on iPhone and removing the double modal on home page
  frontend/src/styles/components/Filters.scss
  frontend/src/styles/components/RecipeDetails.scss
  frontend/src/styles/reset.css
Labels: Reviewed

#37 S4_F02_US3_iphone-fixes: Fixing the inputs and filters issues on iphone and removing the double modal on home page
  frontend/src/styles/components/Filters.scss
  frontend/src/styles/components/RecipeDetails.scss
  frontend/src/styles/reset.css
Labels: Reviewed

#38 S4_F02_US3_iphone-fixes: Removing the double modal
  frontend/src/pages/Home.jsx
Labels: Reviewed

#39 S4_F02_US3_iphone-fixes: Removing the double modal
  frontend/src/pages/Home.jsx
Labels: Reviewed

#40 Fixing the rerender issues
  frontend/src/components/Filters.jsx
  frontend/src/pages/Home.jsx
  frontend/src/pages/Search.jsx
Labels: Reviewed

#41 S4_F03_US6_sort-by-button
  frontend/src/components/RecipesList.jsx
  frontend/src/pages/Search.jsx
  frontend/src/styles/components/RecipesList.scss
  frontend/src/styles/components/SearchPageNavBar.scss
Labels: Reviewed

#42 S3 f04 us4 metabolism calculator
  frontend/src/components/CalculatorInput.jsx
  frontend/src/components/DishTypes.jsx
  frontend/src/components/MetabolismCalculator.jsx
  frontend/src/components/NavBar.jsx
  frontend/src/pages/Home.jsx
  frontend/src/styles/components/MetabolismCalculator.scss
  frontend/src/styles/components/NavBar.scss
Labels: Corrections done

#43 S3 f01 us1 dark mode
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/NavBar.jsx
  frontend/src/pages/Home.jsx
  frontend/src/styles/App.scss
  frontend/src/styles/Search.scss
  frontend/src/styles/components/CategoryButton.scss
  frontend/src/styles/components/MetabolismCalculator.scss
  frontend/src/styles/components/RecipeDetails.scss
  frontend/src/styles/components/RecipesList.scss
  frontend/src/styles/components/SearchPageNavBar.scss
  frontend/src/styles/reset.css
Labels: Reviewed

#44 S4 f03 us8 automatic switch api keys
  frontend/src/pages/Home.jsx
  frontend/src/utils.jsx
Labels: Reviewed, Corrections done

#45 S4 f01 us1 no search results
  frontend/public/assets/logo/logo-not-found.svg
  frontend/src/components/MetabolismCalculator.jsx
  frontend/src/components/NoSearchResults.jsx
  frontend/src/pages/Search.jsx
  frontend/src/styles/components/MetabolismCalculator.scss
  frontend/src/styles/components/NavBar.scss
  frontend/src/styles/components/NoSearchResults.scss
Labels: Reviewed

#46 S3 f03 us7 synchronization of the filters and the query
  frontend/src/components/Filters.jsx
  frontend/src/components/RecipesList.jsx
  frontend/src/components/RoundFilter.jsx
  frontend/src/components/SearchPageNavBar.jsx
  frontend/src/components/SquareFilter.jsx
  frontend/src/pages/Home.jsx
  frontend/src/pages/Search.jsx
  frontend/src/styles/components/Filters.scss
  frontend/src/styles/components/NavBar.scss
  frontend/src/styles/components/SearchPageNavBar.scss
Labels: Reviewed

#47 S4 f03 us9 loading screen
  frontend/public/assets/loading-black.gif
  frontend/public/assets/loading-white.gif
  frontend/src/components/Filters.jsx
  frontend/src/components/LoadingScreen.jsx
  frontend/src/pages/Home.jsx
  frontend/src/pages/Search.jsx
  frontend/src/styles/components/LoadingScreen.scss
Labels: Reviewed

#48 S4 f02 us2 keyboard action
  frontend/src/components/Filters.jsx
  frontend/src/styles/components/LoadingScreen.scss
  frontend/src/styles/components/NoSearchResults.scss
Labels: Reviewed

#50 S3 f01 us2 dark mode
  frontend/src/styles/App.scss
  frontend/src/styles/components/CategoryButton.scss
  frontend/src/styles/components/Filters.scss
  frontend/src/styles/components/NoSearchResults.scss
  frontend/src/styles/components/RecipeCard.scss
Labels: Reviewed

#53 S3 f01 us2 dark mode
  frontend/src/components/Filters.jsx
  frontend/src/styles/App.scss
  frontend/src/styles/components/Filters.scss
  frontend/src/styles/components/MetabolismCalculator.scss
  frontend/src/styles/components/NavBar.scss
  frontend/src/styles/components/RecipeCard.scss
  frontend/src/styles/components/SearchPageNavBar.scss
Labels: Reviewed

#55 S4 f01 us11 scrollbar css
  frontend/src/styles/App.scss
  frontend/src/styles/components/Filters.scss
  frontend/src/styles/components/NavBar.scss
  frontend/src/styles/components/RecipeDetails.scss
Labels: Reviewed

#57 S4_F03_US12_search-results-bug-fixes: Fixing the search error and add…
  frontend/src/pages/Search.jsx
Labels: Reviewed

#58 Dev
  frontend/src/pages/Search.jsx
Labels: Reviewed

#59 S4 fix metabolism style
  frontend/src/styles/components/MetabolismCalculator.scss
  frontend/src/styles/components/SearchPageNavBar.scss
Labels: Reviewed

#60 S4 fix css style loading search bar filters inputs
  .DS_Store
  frontend/src/pages/Search.jsx
  frontend/src/styles/App.scss
  frontend/src/styles/components/Filters.scss
  frontend/src/styles/components/LoadingScreen.scss
  frontend/src/styles/components/NavBar.scss
  frontend/src/styles/components/RecipeDetails.scss
Labels: Reviewed

#61 S4 fix metabolism style
  frontend/src/components/MetabolismCalculator.jsx
  frontend/src/styles/App.scss
Labels: Reviewed

#62 S4 fix modal textdeco
  frontend/src/styles/components/Filters.scss
  frontend/src/styles/components/MetabolismCalculator.scss
  frontend/src/styles/components/RecipeDetails.scss
  frontend/src/styles/reset.css
Labels: Reviewed

#63 Dev
  .DS_Store
  frontend/src/components/MetabolismCalculator.jsx
  frontend/src/pages/Search.jsx
  frontend/src/styles/App.scss
  frontend/src/styles/components/Filters.scss
  frontend/src/styles/components/LoadingScreen.scss
  frontend/src/styles/components/MetabolismCalculator.scss
  frontend/src/styles/components/NavBar.scss
  frontend/src/styles/components/RecipeDetails.scss
  frontend/src/styles/components/SearchPageNavBar.scss
  frontend/src/styles/reset.css
Labels: Reviewed
